#ENC[AES256_GCM,data:IF5ia4jUyprltMkif/oqy3Vrw+WYWDAb,iv:w6RuMh6XUDc0F1B0ioSpP9Ilioooo7mb0H83g1hM7lQ=,tag:XgcwYAaLpyAXxIgNfWbcqw==,type:comment]
secret:
    #ENC[AES256_GCM,data:uKboV2GZsLAxkBAe2mFJQ5PgAcidUrLxPii8VJ7h8kXqs5VSasW39pQ7YqmJxm0=,iv:9cCLivlx9k7kGB7PDr8EcZ9aOoZEYp2rNcth9BTDlYA=,tag:bV7QlFJ/IHcdlJPdHmibgA==,type:comment]
    create: ENC[AES256_GCM,data:W/07Vw==,iv:XKKSgd7RxMJSqmj2oeBZU6fqZLJOY1SkarqMe/gE00k=,tag:PzupM0iQ35uiAK2wmz1xjw==,type:bool]
    data:
        DATABASE_PASSWORD: ENC[AES256_GCM,data:RrY9KZBFt6u/kNKd8STAJhH9CWlcRhZtsNfzjZeo,iv:ZpdMigSP62CDd2OCTJwCySXTMtgHuSmg0O8ElB+UPQI=,tag:cVzmon44J2ZyCIYB0YwsDg==,type:str]
        API_KEY: ENC[AES256_GCM,data:7h7k1j442xKEw+yLKyM0IM4b9iptiYIgR5yZGBs=,iv:HaAwLnyaYQNdU1jo61z0r7qNT4VwK6DEllog8GnrGk4=,tag:sLKX+OtNvWSI0YjdfN/PtQ==,type:str]
sops:
    lastmodified: "2025-09-23T20:46:51Z"
    mac: ENC[AES256_GCM,data:+ysUDuHhdMiUWrOa/C9TpTLUM9w+OOXwFQ4dCHRzhU2hyiv8B/Yf6jfB7LK25bASG4S3kRq0YX4+RVzcitlCTHQ95cebI2X6xH9z/+s8v9FLYBldLWTgjGNngJRIZZVeXlBnND37Nf0qKZ9qVmgKHAjLRVtG9obOV5cVe/DQozo=,iv:eY13ny81vTGmpDo9aYxil5aQ5DWnFhskpUpbcfTrGwk=,tag:ZFu0JLVoXKDQb3YR5lt8DQ==,type:str]
    pgp:
        - created_at: "2025-09-23T20:46:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxlbKTWZsimqAQ/9Ga/a938UxQZ8YrPWjOY/ZNDsOUoX5e/pgc+ZebbJCdb5
            78gZPo25y89dSDIu4soJttUjOzJOBsdRAjwYuKXsqxWMeIbxwTMU9GZU4pq8bC3m
            5IcsClL4cEFb2N2OgC6QLnCxfV+VjEJB2vTCjYIM3gmYhSyBCGhsWjdTD0EB6x8b
            aQxpRDhREXFIb+wl81a5gZJY5mVKi/X2mJA5sNfg5JdSIIs7e9wKM8rBGTjX2QK+
            Zy354MMJUi8LFp+WQ66Xn++beD3qNglqyjr5H/7xMMJfYDk7WqYgWAKDqkCB+yBY
            iLkNFuCjQVdUCiHfU4AAoJMxDT7uF/55ObzUbDb9lYLoArgNetqDaZFW2IgCES1f
            JXNxBcwQqEPhn9HPejly8c1Kzg2JOQAwap9H5f8poInuuPy2WG3eICZRo659C/hS
            2jskbOQGSFOTvxDQ6k8UVPIcpEtnbvOCLpQtsLCL7OMmL+nkZKCwNkF80ZZshtBs
            1H+CR91JcPG/ATCfbVi0bj4olwA7LgQKza7KzyfALJXanrDAY6jmt+li7uinpG2A
            zCS5wzZw226ADANk6Cs78b1BpzDrk6IX9lsgpAHa3K2/QxWATa7IuBZiR9Oy0H2U
            9m7uyEOVj7ydW2QjdAkV5GSYXGkVxMOGrjcVkF+zdRMhDS7lK2M4WXmwZxU9DWXU
            aAEJAhBAyfThLRC8Dk9x8EZ6danSM9ynwADAACuXujfXKsWI1JReFvnsUdTjV1+i
            wDm0rYodGmvtttiIw55tuFA5R7P2TtJ7YeO94pEbK7kok1+1JFXcoQhHzOEDNiZP
            io+NliZ0ub58
            =HJdd
            -----END PGP MESSAGE-----
          fp: 0FCAC3809FAD6910A572F93E7BEE06E2F55FEF62
    unencrypted_suffix: _unencrypted
    version: 3.10.2