name: 'Java Test & Package Action'
description: 'Downloads a workspace, runs tests, and packages the application with a semantic version.'

inputs:
  java-version:
    description: 'JDK version.'
    required: false
    default: '25'
  distribution:
    description: 'JDK distribution (e.g., temurin, corretto).'
    required: false
    default: 'corretto'
  working-directory:
    description: 'Directory of the pom.xml, for monorepos.'
    required: false
    default: 'backend'
  maven-test-args:
    description: 'Extra arguments for the Maven test command.'
    required: false
    default: ''
  maven-package-args:
    description: 'Extra arguments for the Maven package command.'
    required: false
    default: ''
  workspace-artifact-name:
    description: 'Name of the workspace artifact to download.'
    required: false
    default: 'workspace'
  jar-artifact-name:
    description: 'Name for the final uploaded JAR artifact.'
    required: false
    default: 'java-app-jar'

outputs:
  app-version:
    description: "The generated semantic version for the application."
    value: ${{ steps.generate-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Set up JDK with Maven caching
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: 'maven'
        cache-dependency-path: ${{ inputs.working-directory }}/pom.xml

    - name: Download Workspace
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.workspace-artifact-name }}
        path: .

    - name: Run Tests with Maven
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mvn -B test ${{ inputs.maven-test-args }}

    - name: Get base version from pom.xml
      id: get-version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: echo "base_version=$(mvn help:evaluate -Dexpression=project.base.version -q -DforceStdout)" >> $GITHUB_OUTPUT

    - name: Generate Semantic Version
      id: generate-version
      shell: bash
      run: |
        VERSION="${{ steps.get-version.outputs.base_version }}.${{ github.run_number }}-$(date +'%Y%m%d').${GITHUB_SHA::7}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Generated version: ${VERSION}"

    - name: Package Application with new version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mvn -B package -DskipTests -Drevision=${{ steps.generate-version.outputs.version }} ${{ inputs.maven-package-args }}

    - name: Rename JAR for consistency
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      # Use the dynamically generated version to find and rename the correct JAR file.
      run: mv target/interview-${{ steps.generate-version.outputs.version }}.jar target/app.jar

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.jar-artifact-name }}
        path: ${{ inputs.working-directory }}/target/app.jar

