name: 'Java Test & Package Action'
description: 'Downloads a workspace, runs tests, packages the application, and sets the version.'

inputs:
  java-version:
    description: 'JDK version.'
    required: false
    default: '25'
  distribution:
    description: 'JDK distribution (e.g., temurin, corretto).'
    required: false
    default: 'corretto'
  working-directory:
    description: 'Directory of the pom.xml, for monorepos.'
    required: false
    default: 'backend'
  maven-test-args:
    description: 'Extra arguments for the Maven test command.'
    required: false
    default: ''
  maven-package-args:
    description: 'Extra arguments for the Maven package command.'
    required: false
    default: ''
  workspace-artifact-name:
    description: 'Name of the workspace artifact to download.'
    required: false
    default: 'workspace'
  jar-artifact-name:
    description: 'Name for the final uploaded JAR artifact.'
    required: false
    default: 'java-app-jar'

outputs:
  app-version:
    description: "The generated application version."
    value: ${{ steps.get_version.outputs.app_version }}

runs:
  using: "composite"
  steps:
    - name: Set up JDK with Maven caching
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: 'maven'
        cache-dependency-path: ${{ inputs.working-directory }}/pom.xml

    - name: Download Workspace
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.workspace-artifact-name }}
        path: .

    - name: Generate Application Version
      id: get_version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        BASE_VERSION=$(mvn help:evaluate -Dexpression=project.base.version -q -DforceStdout)
        BUILD_NUMBER=${{ github.run_number }}
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        BUILD_DATE=$(date -u +'%Y%m%d')
        # Create a SemVer compatible version: MAJOR.MINOR.PATCH-METADATA
        APP_VERSION="${BASE_VERSION}.${BUILD_NUMBER}-${BUILD_DATE}.${SHORT_SHA}"
        echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT

    - name: Run Tests with Maven
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mvn -B test -Drevision=${{ steps.get_version.outputs.app_version }} ${{ inputs.maven-test-args }}

    - name: Package Application
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mvn -B package -DskipTests -Drevision=${{ steps.get_version.outputs.app_version }} ${{ inputs.maven-package-args }}

    - name: Determine JAR path from pom.xml
      id: determine-jar-path
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        FINAL_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)
        JAR_PATH="target/${FINAL_NAME}.jar"
        echo "path=${JAR_PATH}" >> $GITHUB_OUTPUT

    - name: Rename JAR for consistency
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mv ${{ steps.determine-jar-path.outputs.path }} target/app.jar

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.jar-artifact-name }}
        path: ${{ inputs.working-directory }}/target/app.jar


