name: 'Publish Helm Chart Action'
description: 'Packages and publishes a Helm chart to ChartMuseum.'

inputs:
  chart-path:
    description: 'The path to the Helm chart directory.'
    required: true
  chartmuseum-url:
    description: 'The URL of the ChartMuseum instance.'
    required: true
  app-version:
    description: 'The version of the application to set in the chart.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: 'v3.13.0'

    - name: Install helm-push plugin
      shell: bash
      # This plugin provides the 'cm-push' command for uploading charts to ChartMuseum.
      # See more: https://github.com/chartmuseum/helm-push
      run: |
        helm plugin install https://github.com/chartmuseum/helm-push || true
        helm plugin list | grep 'cm-push' || (echo "helm-push plugin installation failed" && exit 1)

    - name: Package Helm Chart
      id: package_chart
      shell: bash
      run: |
        # We package the chart and dynamically inject the correct application and chart version.
        helm package ${{ inputs.chart-path }} --version ${{ inputs.app-version }} --app-version ${{ inputs.app-version }}

        # Find the packaged chart file in the current directory.
        PACKAGE_FILE=$(ls *.tgz)
        echo "packaged_chart=${PACKAGE_FILE}" >> $GITHUB_OUTPUT

    - name: Push chart using helm-push
      shell: bash
      run: helm cm-push ${{ steps.package_chart.outputs.packaged_chart }} ${{ inputs.chartmuseum-url }}

