{{- range $name, $job := .Values.cronjobs }}
{{- if $job.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "helm.fullname" $ }}-{{ $name }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
spec:
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: {{ $job.concurrencyPolicy | default "Allow" }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "helm.selectorLabels" $ | nindent 12 }}
            app.kubernetes.io/component: cronjob-{{ $name }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "helm.serviceAccountName" $ }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ $name }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
              imagePullPolicy: {{ $job.image.pullPolicy }}
              {{- with $job.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $job.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $job.envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml $job.resources | nindent 16 }}
{{- end }}
{{- end }}