{{- if and .Values.horizontalPodAutoscaler.enabled ( not .Values.verticalPodAutoscaler.enabled ) }}
# Using the stable autoscaling/v2 API, which is supported by the
# Kubernetes version specified in Chart.yaml (>=1.23.0-0).
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helm.fullname" . }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas }}
  metrics:
    {{- if .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}