# Name of the workflow, displayed in the GitHub Actions tab.
name: Tekmetric Backend CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

# Ensures that only one workflow run is in progress for a specific PR or branch.
# See more: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with reusable action
        uses: ./.github/actions/java-build
        with:
          working-directory: 'backend'

  test:
    name: Test & Package Application
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version: ${{ steps.test_package.outputs.app-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test & Package
        id: test_package
        uses: ./.github/actions/java-test
        with:
          working-directory: 'backend'
          jar-artifact-name: 'java-app-jar'

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    outputs:
      image-name: ${{ steps.repo-owner.outputs.name }}/tekmetric-backend
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get lowercase repository owner
        id: repo-owner
        run: echo "name=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        id: build_and_push
        uses: ./.github/actions/docker-build
        with:
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ steps.repo-owner.outputs.name }}/tekmetric-backend
          tags: |
            type=sha,prefix=
            type=raw,value=${{ needs.test.outputs.version }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          # Only push the image when the workflow runs on the master branch
          push-image: ${{ github.ref == 'refs/heads/master' }}
          working-directory: 'backend'
          jar-artifact-name: 'java-app-jar'

      - name: Add Image URL to Job Summary
        # See more: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
        run: |
          echo "### Docker Image Published" >> $GITHUB_STEP_SUMMARY
          echo "The following image tags were pushed to the registry:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.build_and_push.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  scan-image:
    name: Scan Docker Image for Vulnerabilities
    runs-on: ubuntu-latest
    needs: [docker-build, test]
    permissions:
      contents: read # for checkout
      packages: read # to pull the image from GHCR
      security-events: write # to upload SARIF results to GitHub Security tab
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan Docker Image
        uses: ./.github/actions/scan-image
        with:
          image-ref: 'ghcr.io/${{ needs.docker-build.outputs.image-name }}:${{ needs.test.outputs.version }}'
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "TODO: Download artifacts and run SonarCloud/etc."
        working-directory: ./backend
        run: echo "This job will perform code quality checks on the source code."

  publish-chart:
    name: Publish Helm Chart
    runs-on: self-hosted # As requested for local ChartMuseum
    needs: [scan-image] # Run after the scan passes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Helm Chart
        uses: ./.github/actions/publish-chart
        with:
          chart-path: './backend/src/main/helm/backend-service-chart'
          chart-version: ${{ needs.test.outputs.version }}
          app-version: ${{ needs.test.outputs.version }}
          chartmuseum-url: 'http://localhost:9090'
          force: 'false'

