# Name of the workflow, displayed in the GitHub Actions tab.
name: Tekmetric Backend CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

# Ensures that only one workflow run is in progress for a specific PR or branch.
# See more: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with reusable action
        uses: ./.github/actions/java-build
        with:
          working-directory: 'backend'

  test:
    name: Test, Package & Create JRE
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test, Package & Create Custom JRE
        uses: ./.github/actions/java-test
        with:
          working-directory: 'backend'
          jar-artifact-name: 'java-app-jar'
          jre-artifact-name: 'custom-jre'

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        id: build_and_push
        uses: ./.github/actions/docker-build
        with:
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ github.repository_owner }}/tekmetric-backend
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          # Only push the image when the workflow runs on the master branch
          push-image: ${{ github.ref == 'refs/heads/master' }}
          working-directory: 'backend'
          jar-artifact-name: 'java-app-jar'
          jre-artifact-name: 'custom-jre'

      - name: Add Image URL to Job Summary
        # See more: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
        run: |
          echo "### Docker Image Published" >> $GITHUB_STEP_SUMMARY
          echo "The following image tags were pushed to the registry:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.build_and_push.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "TODO: Download artifacts and run SonarCloud/etc."
        working-directory: ./backend
        run: echo "This job will perform code quality checks on the source code."

