# Name of the workflow, displayed in the GitHub Actions tab.
name: Tekmetric Backend CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

# Ensures that only one workflow run is in progress for a specific PR or branch.
# See more: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Application
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with reusable action
        uses: ./.github/actions/java-build
        with:
          working-directory: 'backend'

  test:
    name: Test and Package Application
    runs-on: self-hosted
    needs: build
    steps:
      - name: Test and Package
        uses: ./.github/actions/java-test
        with:
          working-directory: 'backend'

  code-quality:
    name: Code Quality Analysis
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "TODO: Download artifacts and run SonarCloud/etc."
        run: echo "This job will perform code quality checks on the source code."

